name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: phpunit-latest
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.0
      - name: phpunit-lowest
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.3

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: phpstan
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          php_version: 8.0

  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: phpstan
        uses: docker://vimeo/psalm-github-actions
        with:
          php_version: 8.0
